version: "3"

tasks:
  up:
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - test -f docker-compose.yaml
    cmds:
      - docker-compose up {{.build}}
  down:
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - test -f docker-compose.yaml
    cmds:
      - docker-compose down
  abi-gen:
    cmds:
      - jq '.abi' ../contracts/artifacts/contracts/AAA.sol/AAA.json > AAA.abi
      - abigen --abi AAA.abi --pkg bindings --type AAA --out api/aaa/bindings/aaa.go
      - rm AAA.abi
