version: "3"

tasks:
  up:*:
    vars:
      build: "{{index .MATCH 0}}"
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - test -f docker-compose.yaml
    cmds:
      - docker-compose up {{.build}} -d
  down:
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - test -f docker-compose.yaml
    cmds:
      - docker-compose down
  abi-gen:
    cmds:
      - jq '.abi' ../contracts/artifacts/contracts/AAAContract.sol/AAAContract.json > AAAContract.abi
      - abigen --abi AAAContract.abi --pkg bindings --type AAAContract --out api/aaa/bindings/aaa_contract.go
      - rm AAAContract.abi
