/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AAASmartContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TOTAL_SEED_WORDS"
      | "checkSACExistenceAndAssociation"
      | "encryptedSidForPid"
      | "encryptedWordsForUser"
      | "getEncryptedSeedPhraseAndSID"
      | "getPIDFromSID"
      | "isNIP"
      | "isUIP"
      | "owner"
      | "pidToSid"
      | "pidToUserPublicKey"
      | "redundantEncryptedWords"
      | "registerNIP"
      | "registerSACAssociation"
      | "registerUIP"
      | "requestSeedPhraseProtocol"
      | "sacToAnonymousAccountPk"
      | "seedPhraseProtocolInitiated"
      | "sidPidSymkAssociation"
      | "submitEncryptedWordFragment"
      | "submitRedundantEncryptedWord"
      | "wordsReceivedCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EncryptedWordFragmentSubmitted"
      | "PidSidAssociationRetrieved"
      | "SacRegistered"
      | "SeedPhraseProtocolInitiated"
      | "SidCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TOTAL_SEED_WORDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkSACExistenceAndAssociation",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedSidForPid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedWordsForUser",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSeedPhraseAndSID",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPIDFromSID",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isNIP", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "isUIP", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pidToSid", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pidToUserPublicKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redundantEncryptedWords",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNIP",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSACAssociation",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUIP",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSeedPhraseProtocol",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sacToAnonymousAccountPk",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "seedPhraseProtocolInitiated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sidPidSymkAssociation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedWordFragment",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRedundantEncryptedWord",
    values: [BytesLike, BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wordsReceivedCount",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "TOTAL_SEED_WORDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSACExistenceAndAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedSidForPid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedWordsForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSeedPhraseAndSID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPIDFromSID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isNIP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isUIP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pidToSid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pidToUserPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redundantEncryptedWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNIP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSACAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUIP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSeedPhraseProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sacToAnonymousAccountPk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seedPhraseProtocolInitiated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sidPidSymkAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedWordFragment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRedundantEncryptedWord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wordsReceivedCount",
    data: BytesLike
  ): Result;
}

export namespace EncryptedWordFragmentSubmittedEvent {
  export type InputTuple = [
    pid: BytesLike,
    wordNumber: BigNumberish,
    uipNode: AddressLike
  ];
  export type OutputTuple = [pid: string, wordNumber: bigint, uipNode: string];
  export interface OutputObject {
    pid: string;
    wordNumber: bigint;
    uipNode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PidSidAssociationRetrievedEvent {
  export type InputTuple = [sid: BytesLike, encryptedPid: string];
  export type OutputTuple = [sid: string, encryptedPid: string];
  export interface OutputObject {
    sid: string;
    encryptedPid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SacRegisteredEvent {
  export type InputTuple = [sac: BytesLike, anonymousAccountPk: string];
  export type OutputTuple = [sac: string, anonymousAccountPk: string];
  export interface OutputObject {
    sac: string;
    anonymousAccountPk: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeedPhraseProtocolInitiatedEvent {
  export type InputTuple = [pid: BytesLike, userPk: string];
  export type OutputTuple = [pid: string, userPk: string];
  export interface OutputObject {
    pid: string;
    userPk: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SidCreatedEvent {
  export type InputTuple = [pid: BytesLike, sid: BytesLike];
  export type OutputTuple = [pid: string, sid: string];
  export interface OutputObject {
    pid: string;
    sid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AAASmartContract extends BaseContract {
  connect(runner?: ContractRunner | null): AAASmartContract;
  waitForDeployment(): Promise<this>;

  interface: AAASmartContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TOTAL_SEED_WORDS: TypedContractMethod<[], [bigint], "view">;

  checkSACExistenceAndAssociation: TypedContractMethod<
    [_sac: BytesLike, _anonymousAccountPk: string],
    [boolean],
    "view"
  >;

  encryptedSidForPid: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  encryptedWordsForUser: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedSeedPhraseAndSID: TypedContractMethod<
    [_pid: BytesLike],
    [
      [string[], string, string, string] & {
        encryptedWords: string[];
        encryptedSID: string;
        symkEncryptedPidSidAssociation: string;
        pkUserForSidEncryption: string;
      }
    ],
    "view"
  >;

  getPIDFromSID: TypedContractMethod<[_sid: BytesLike], [string], "view">;

  isNIP: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isUIP: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pidToSid: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  pidToUserPublicKey: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  redundantEncryptedWords: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: AddressLike],
    [string],
    "view"
  >;

  registerNIP: TypedContractMethod<
    [_nipAddress: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  registerSACAssociation: TypedContractMethod<
    [_sac: BytesLike, _anonymousAccountPk: string],
    [void],
    "nonpayable"
  >;

  registerUIP: TypedContractMethod<
    [_uipAddress: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  requestSeedPhraseProtocol: TypedContractMethod<
    [_pid: BytesLike, _userPk: string],
    [void],
    "nonpayable"
  >;

  sacToAnonymousAccountPk: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  seedPhraseProtocolInitiated: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  sidPidSymkAssociation: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  submitEncryptedWordFragment: TypedContractMethod<
    [_pid: BytesLike, _wordNumber: BigNumberish, _encryptedWord: string],
    [void],
    "nonpayable"
  >;

  submitRedundantEncryptedWord: TypedContractMethod<
    [
      _pid: BytesLike,
      _originalWordNumber: BigNumberish,
      _encryptedWord: string,
      _targetUipNodeAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  wordsReceivedCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TOTAL_SEED_WORDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkSACExistenceAndAssociation"
  ): TypedContractMethod<
    [_sac: BytesLike, _anonymousAccountPk: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "encryptedSidForPid"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "encryptedWordsForUser"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedSeedPhraseAndSID"
  ): TypedContractMethod<
    [_pid: BytesLike],
    [
      [string[], string, string, string] & {
        encryptedWords: string[];
        encryptedSID: string;
        symkEncryptedPidSidAssociation: string;
        pkUserForSidEncryption: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPIDFromSID"
  ): TypedContractMethod<[_sid: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isNIP"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUIP"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pidToSid"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "pidToUserPublicKey"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "redundantEncryptedWords"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerNIP"
  ): TypedContractMethod<
    [_nipAddress: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerSACAssociation"
  ): TypedContractMethod<
    [_sac: BytesLike, _anonymousAccountPk: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUIP"
  ): TypedContractMethod<
    [_uipAddress: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestSeedPhraseProtocol"
  ): TypedContractMethod<
    [_pid: BytesLike, _userPk: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sacToAnonymousAccountPk"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "seedPhraseProtocolInitiated"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sidPidSymkAssociation"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "submitEncryptedWordFragment"
  ): TypedContractMethod<
    [_pid: BytesLike, _wordNumber: BigNumberish, _encryptedWord: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRedundantEncryptedWord"
  ): TypedContractMethod<
    [
      _pid: BytesLike,
      _originalWordNumber: BigNumberish,
      _encryptedWord: string,
      _targetUipNodeAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wordsReceivedCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "EncryptedWordFragmentSubmitted"
  ): TypedContractEvent<
    EncryptedWordFragmentSubmittedEvent.InputTuple,
    EncryptedWordFragmentSubmittedEvent.OutputTuple,
    EncryptedWordFragmentSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "PidSidAssociationRetrieved"
  ): TypedContractEvent<
    PidSidAssociationRetrievedEvent.InputTuple,
    PidSidAssociationRetrievedEvent.OutputTuple,
    PidSidAssociationRetrievedEvent.OutputObject
  >;
  getEvent(
    key: "SacRegistered"
  ): TypedContractEvent<
    SacRegisteredEvent.InputTuple,
    SacRegisteredEvent.OutputTuple,
    SacRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SeedPhraseProtocolInitiated"
  ): TypedContractEvent<
    SeedPhraseProtocolInitiatedEvent.InputTuple,
    SeedPhraseProtocolInitiatedEvent.OutputTuple,
    SeedPhraseProtocolInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "SidCreated"
  ): TypedContractEvent<
    SidCreatedEvent.InputTuple,
    SidCreatedEvent.OutputTuple,
    SidCreatedEvent.OutputObject
  >;

  filters: {
    "EncryptedWordFragmentSubmitted(bytes32,uint256,address)": TypedContractEvent<
      EncryptedWordFragmentSubmittedEvent.InputTuple,
      EncryptedWordFragmentSubmittedEvent.OutputTuple,
      EncryptedWordFragmentSubmittedEvent.OutputObject
    >;
    EncryptedWordFragmentSubmitted: TypedContractEvent<
      EncryptedWordFragmentSubmittedEvent.InputTuple,
      EncryptedWordFragmentSubmittedEvent.OutputTuple,
      EncryptedWordFragmentSubmittedEvent.OutputObject
    >;

    "PidSidAssociationRetrieved(bytes32,string)": TypedContractEvent<
      PidSidAssociationRetrievedEvent.InputTuple,
      PidSidAssociationRetrievedEvent.OutputTuple,
      PidSidAssociationRetrievedEvent.OutputObject
    >;
    PidSidAssociationRetrieved: TypedContractEvent<
      PidSidAssociationRetrievedEvent.InputTuple,
      PidSidAssociationRetrievedEvent.OutputTuple,
      PidSidAssociationRetrievedEvent.OutputObject
    >;

    "SacRegistered(bytes32,string)": TypedContractEvent<
      SacRegisteredEvent.InputTuple,
      SacRegisteredEvent.OutputTuple,
      SacRegisteredEvent.OutputObject
    >;
    SacRegistered: TypedContractEvent<
      SacRegisteredEvent.InputTuple,
      SacRegisteredEvent.OutputTuple,
      SacRegisteredEvent.OutputObject
    >;

    "SeedPhraseProtocolInitiated(bytes32,string)": TypedContractEvent<
      SeedPhraseProtocolInitiatedEvent.InputTuple,
      SeedPhraseProtocolInitiatedEvent.OutputTuple,
      SeedPhraseProtocolInitiatedEvent.OutputObject
    >;
    SeedPhraseProtocolInitiated: TypedContractEvent<
      SeedPhraseProtocolInitiatedEvent.InputTuple,
      SeedPhraseProtocolInitiatedEvent.OutputTuple,
      SeedPhraseProtocolInitiatedEvent.OutputObject
    >;

    "SidCreated(bytes32,bytes32)": TypedContractEvent<
      SidCreatedEvent.InputTuple,
      SidCreatedEvent.OutputTuple,
      SidCreatedEvent.OutputObject
    >;
    SidCreated: TypedContractEvent<
      SidCreatedEvent.InputTuple,
      SidCreatedEvent.OutputTuple,
      SidCreatedEvent.OutputObject
    >;
  };
}
