// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Michele Dinelli",
            "email": "m.dinelli@unibo.it"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/pac": {
            "post": {
                "description": "Allows a user to request a Public Authentication Code (PAC). It accepts a message ` + "`" + `PID` + "`" + ` and ` + "`" + `SIGN(PID, SK)` + "`" + `, namely the PID signed with the private key of the public-private key pair used to obtain the PID.  When logging onto the public service, the user can show the PAC, and the service has only to query the NIP to verify that the code is associated with an authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "PAC issuance request",
                "parameters": [
                    {
                        "description": "PAC Request Model",
                        "name": "models.PACRequestModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PACRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The Public Authentication Code",
                        "schema": {
                            "$ref": "#/definitions/models.PACResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        },
        "/v1/auth/sac": {
            "post": {
                "description": "The SAC (Secret Authentication Code) is a one-time code used to authenticate the user as an anonymous user. It accepts ` + "`" + `ENC(SID, SK)` + "`" + `, i.e., the SID signed with the private key associated with the public key saved on the blockchain at the moment of seed phrase creation and used in the record where the SID was stored. The NIP retrieves the SID record from the blockchain and checks that it was actually signed by that user via the PK saved in the record. This certifies that the user is the true owner of that SID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "SAC issuance request",
                "parameters": [
                    {
                        "description": "SAC Request Model",
                        "name": "models.SACRequestModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SACRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The Secret Authentication Code",
                        "schema": {
                            "$ref": "#/definitions/models.SACResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        },
        "/v1/auth/verify-pac": {
            "post": {
                "description": "Allows a user to verify a PAC (Public Authentication Code) for services accepting an authenticated anonymous identity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "PAC verification request",
                "parameters": [
                    {
                        "description": "PAC Verification Request Model",
                        "name": "models.PACVerificationRequestModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PACVerificationRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The Public Authentication Code Verification Response",
                        "schema": {
                            "$ref": "#/definitions/models.PACVerificationResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        },
        "/v1/identity/pid": {
            "post": {
                "description": "The NIP issues a Public Identity Data (PID), i.e., an anonymous token that identifies the user without sharing information. The real identity of the user is carried by the PID alone. The NIP will be the only one able to connect a PID to the real information of the respective user. It accepts a 2048 bit RSA PKCS#8 key encoded in base64.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "PID issuance request",
                "parameters": [
                    {
                        "description": "PID Request Model",
                        "name": "models.PIDRequestModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PIDRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The PID",
                        "schema": {
                            "$ref": "#/definitions/models.PIDResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    },
                    "500": {
                        "description": "An error occurred",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponseModel": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.PACRequestModel": {
            "type": "object",
            "required": [
                "pid",
                "signed_pid"
            ],
            "properties": {
                "pid": {
                    "type": "string",
                    "example": "DmIq8x2JNs+E2qGBr16LxP6lUK+i/5nJRLuzvYEymtY="
                },
                "signed_pid": {
                    "type": "string",
                    "example": "signed_pid_payload_base64"
                }
            }
        },
        "models.PACResponseModel": {
            "type": "object",
            "properties": {
                "expiration": {
                    "type": "string",
                    "example": "2024-12-31T23:59:59Z"
                },
                "pac": {
                    "type": "integer",
                    "example": 874532
                }
            }
        },
        "models.PACVerificationRequestModel": {
            "type": "object",
            "required": [
                "pac",
                "pid"
            ],
            "properties": {
                "pac": {
                    "type": "integer",
                    "example": 874532
                },
                "pid": {
                    "type": "string",
                    "example": "DmIq8x2JNs+E2qGBr16LxP6lUK+i/5nJRLuzvYEymtY="
                }
            }
        },
        "models.PACVerificationResponseModel": {
            "type": "object",
            "properties": {
                "expiration": {
                    "type": "string",
                    "example": "2024-12-31T23:59:59Z"
                },
                "valid": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.PIDRequestModel": {
            "type": "object",
            "required": [
                "public_key"
            ],
            "properties": {
                "public_key": {
                    "type": "string",
                    "example": "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1aVRTYzZMY3NmaFRZbEY0WDk2OApEcStXVzNrRmx3U21UR2NJQXJ5eFZ2OVhBQ2VFSXJuL0JYZE9McTFNSU52enc5WTZvNmhTd3hqUkp2SzlvdFpMCnlXYzFvc2RUNGdlTDJaT2xEMHUwakFvbEpqVU9hVWVyMmJKQTUzQzhXMjd1MHJyQzVvc3Z3THRNVWYxWnpTR0MKL2hrY0VOcjNjRGl6YWJibkw2dzVFUEdCVjlNU2RnaUdlelJXaXVEeGIzcldEOFNwSlpNa2c5b3ZSK3dOMlI2YwpOK2RwTkNjdDdWYjQxaWhXU0VXT1o2djhFdTREV3FjVW0vQzBpLzZ3eVJkWU93Y0E3NktkMmkxcnNZdHFlQS84CnZuMklTTEp2eGdkM3ZCdXY1ZnFkS0kzRm0rd3NIVDhHdHlkQUw5VjF4V3g4bnFlcFlwMlIvaXJMNHFUeGFnVzkKMXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
                }
            }
        },
        "models.PIDResponseModel": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "PID successfully issued and saved"
                },
                "pid": {
                    "type": "string",
                    "example": "Nifl3y+2jmuAxF26jqpjogu0ZYnA6IxSikjmTnnjm7k="
                }
            }
        },
        "models.SACRequestModel": {
            "type": "object",
            "required": [
                "sid",
                "signed_sid"
            ],
            "properties": {
                "sid": {
                    "type": "string",
                    "example": "MHhhOTcwZWRkMTEyNTRjNTQ3OTIyMWVjOTFjZGU0YjNiMGI2MjQ1NzI3NmVmMzA0MmMzN2M2MDJkMWRlMTg4Njc5"
                },
                "signed_sid": {
                    "type": "string",
                    "example": "QEZZSiBAF1TPbSgHAlcwlrG4unRGZBGYOf8yjiSfP8wUcnkvdm+yQTOzGpqWG/m4/qCG7stlDYqZrQIyRWC7mb0sbTe2MhMYrZOzyz6uH8hCxIJh5JQ6ivsntufaeg9HOoZ9M6wdhp1/BsbwuGG27CQ7BcuuKZu2Mi1cNu32dnTGxv4PORoCy1JqgV519JsuwL3aekdZ2jVrYaepTTDT1vJR4vhLZ76gV1ywUAIEMm8q+R12ydntAroOd8EaiCXx0pyM3zVAE1G0Qv1g0qRGrnogmMhCIpljJ79KEFtOQDHLd0RnbPuoh99eszx99qc911VXTjiHMNdIxhanp31odA=="
                }
            }
        },
        "models.SACResponseModel": {
            "type": "object",
            "properties": {
                "expiration": {
                    "type": "string",
                    "example": "2024-12-31T23:59:59Z"
                },
                "sac": {
                    "type": "integer",
                    "example": 874532
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "National Identity Provider (NIP)",
	Description:      "API specification for the Authenticated Anonymity Architecture (AAA), a blockchain-based solution providing robust and ethical authenticated anonymous identities with deanonymization capabilities for criminal activity cases.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
